/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.TimeZone;
import javax.swing.JOptionPane;
import logica.Control;
import negocio.Cliente;
import negocio.PlatilloMenu;
import vista.panelesVenta.PanelVentaCredito;
import vista.panelesVenta.PanelVentaPlatillo;

/**
 *
 * @author ed000
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    private int diaSemanaActual;
    private String categoriaMenu;
    private ArrayList<PlatilloMenu> menuDiaCategoria;
    private ArrayList<Cliente> listaClientesOrdenada;
    private Color colorInactivo;

    public Ventas() {
        initComponents();
        colorInactivo = btnVentaCredito.getBackground();
        ////////////////// Se calcula la fecha de hoy
        GregorianCalendar hoy = new GregorianCalendar(TimeZone.getTimeZone("GMT-7"),
                Locale.FRENCH);
        //Se obtiene el día de la semana en base a Calendar(Domingo = 1, Lunes = 2, etc.)
        diaSemanaActual = hoy.get(Calendar.DAY_OF_WEEK);
        // Si el día de la semana es domingo
        if (diaSemanaActual == 1) {
            // Se establece el dia real (Domingo = 7)
            diaSemanaActual = 7;
        } // Si es Lunes u otro
        else {
            // Se establece el dia real
            diaSemanaActual--;
        }
        //////////////////////////////////////

        //////// Calcula la categoría
        // Obtiene la hora del día (0-24)
        int horaDelDia = hoy.get(Calendar.HOUR_OF_DAY);
        // Establece la categoría que se usará para consultar el menú
        if (horaDelDia < 11) {
            categoriaMenu = "DESAYUNO";
        } else if (horaDelDia < 5) {
            categoriaMenu = "COMIDA";
        } else {
            categoriaMenu = "CENA";
        }
        //////////////////////////////////////////////
        // Maximiza la ventana
        this.setExtendedState(MAXIMIZED_BOTH);
        btnVentaPlatillo.setBackground(Color.green);
        ///// Establecer el tipo de venta por default (platillo)
        // Se obtiene el menu de acuerdo al dia de la semana y la hora (categoría) para enviarlo posteriormente
        menuDiaCategoria = Control.menu.consultarMenuDiaCategoria(diaSemanaActual, categoriaMenu);
        // Se agrega el tab de venta de platillos con los parámetros calculados
        tabContenedor.addTab("", new PanelVentaPlatillo(this, diaSemanaActual, categoriaMenu, menuDiaCategoria));
// Se obtiene la lista ordenada de todos los clientes
listaClientesOrdenada = Control.clientes.consultarListaOrdenada();
// Se agrega el tab de venta de créditos
        tabContenedor.addTab("", new PanelVentaCredito(this, listaClientesOrdenada));
        tabContenedor.setLayout(new CardLayout());

        // Si no hay menú para el dia y la categoría
        if (!hayMenu()) {
         // El tipo de venta por default será de crédito
         cambiarACredito();
        }

    }

    private boolean hayMenu() {
        return menuDiaCategoria.size() > 0;
    }

    private void cambiarAPlatillos() {
        btnVentaCredito.setBackground(colorInactivo);
        btnVentaPlatillo.setBackground(Color.green);
        tabContenedor.setSelectedIndex(0);
    }

    private void cambiarACredito() {
        btnVentaPlatillo.setBackground(colorInactivo);
        btnVentaCredito.setBackground(Color.green);
        tabContenedor.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVentaPlatillo = new javax.swing.JButton();
        btnVentaCredito = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        tabContenedor = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta");

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("NUEVA VENTA");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnVentaPlatillo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnVentaPlatillo.setText("Platillo");
        btnVentaPlatillo.setFocusable(false);
        btnVentaPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaPlatilloActionPerformed(evt);
            }
        });

        btnVentaCredito.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnVentaCredito.setText("Crédito");
        btnVentaCredito.setFocusable(false);
        btnVentaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaCreditoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnVentaPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVentaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVentaPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/768px-Back_Arrow.svg.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setFocusable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabContenedor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(0, 371, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(tabContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentaPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaPlatilloActionPerformed
        // Si hay platillos en el menú    
        if(hayMenu()){
            // Por default e muestra la centa de platillos
                 cambiarAPlatillos();
                 System.out.println(menuDiaCategoria.size());
            }
            else{
               // Se muestra mensaje indicando que no hay
               JOptionPane.showMessageDialog(this,
                       "No se ha establecido un menú de "+categoriaMenu.toLowerCase(Locale.US)+" para hoy.",
                       "Imposible",
                       JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_btnVentaPlatilloActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        dispose();

    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVentaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaCreditoActionPerformed
        cambiarACredito();
    }//GEN-LAST:event_btnVentaCreditoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentaCredito;
    private javax.swing.JButton btnVentaPlatillo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabContenedor;
    // End of variables declaration//GEN-END:variables
}
