/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panelesVenta;

import java.awt.Component;
import java.awt.Container;
import java.awt.Frame;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Control;
import negocio.Cliente;
import negocio.Venta;
import negocio.VentaCredito;
import vista.ConfirmacionVenta;

/**
 *
 * @author ed000
 */
public class PanelVentaCredito extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentaCredito
     */
    private Frame parent;
    private ArrayList<Cliente> listaClientes;
    private float total = 0f;

    public PanelVentaCredito(Frame parent, ArrayList<Cliente> listaClientes) {
        initComponents();
        this.parent = parent;
        this.listaClientes = listaClientes;
        establecerClientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboClientes = new javax.swing.JComboBox<>();
        checkBoxNuevoCli = new javax.swing.JCheckBox();
        campoNombreCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCantCena = new javax.swing.JSpinner();
        txtCostoDesayuno = new javax.swing.JSpinner();
        txtCantComida = new javax.swing.JSpinner();
        txtCantDesayuno = new javax.swing.JSpinner();
        txtCostoComida = new javax.swing.JSpinner();
        txtCostoCena = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        checkBoxImprimirNota = new javax.swing.JCheckBox();
        btnRealizarVenta = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1101, 589));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("1. Seleccione el cliente");

        comboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------SIN CLIENTES  DISPONIBLES------" }));
        comboClientes.setEnabled(false);
        comboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientesActionPerformed(evt);
            }
        });

        checkBoxNuevoCli.setText("Cliente nuevo");
        checkBoxNuevoCli.setEnabled(false);
        checkBoxNuevoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNuevoCliActionPerformed(evt);
            }
        });

        campoNombreCliente.setEnabled(false);
        campoNombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNombreClienteKeyReleased(evt);
            }
        });

        txtNombreCliente.setText("Nombre del cliente:");
        txtNombreCliente.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCliente)
                    .addComponent(checkBoxNuevoCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(checkBoxNuevoCli))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("2. Indique los créditos a vender");

        jLabel4.setText("DESAYUNOS");

        jLabel5.setText("COMIDAS");

        jLabel6.setText("CENAS");

        jLabel7.setText("Cantidad");

        txtCantCena.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        txtCantCena.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCantCenaStateChanged(evt);
            }
        });

        txtCostoDesayuno.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        txtCostoDesayuno.setEnabled(false);
        txtCostoDesayuno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCostoDesayunoStateChanged(evt);
            }
        });

        txtCantComida.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        txtCantComida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCantComidaStateChanged(evt);
            }
        });

        txtCantDesayuno.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        txtCantDesayuno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCantDesayunoStateChanged(evt);
            }
        });

        txtCostoComida.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        txtCostoComida.setEnabled(false);
        txtCostoComida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCostoComidaStateChanged(evt);
            }
        });

        txtCostoCena.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        txtCostoCena.setEnabled(false);
        txtCostoCena.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCostoCenaStateChanged(evt);
            }
        });

        jLabel8.setText("$");

        jLabel9.setText("$");

        jLabel10.setText("$");

        jLabel11.setText("Costo");

        jLabel12.setText("TOTAL:  $");

        txtTotal.setText("0.00");

        checkBoxImprimirNota.setText("Imprimir nota");
        checkBoxImprimirNota.setEnabled(false);
        checkBoxImprimirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxImprimirNotaActionPerformed(evt);
            }
        });

        btnRealizarVenta.setText("REALIZAR VENTA");
        btnRealizarVenta.setEnabled(false);
        btnRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCamposLayout = new javax.swing.GroupLayout(panelCampos);
        panelCampos.setLayout(panelCamposLayout);
        panelCamposLayout.setHorizontalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelCamposLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3))
                                .addGroup(panelCamposLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(45, 45, 45)
                                    .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCantComida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCantCena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7)
                            .addGroup(panelCamposLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(45, 45, 45)
                                .addComponent(txtCantDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCamposLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtCostoDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelCamposLayout.createSequentialGroup()
                                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCostoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCostoCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal))
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(checkBoxImprimirNota))
                    .addGroup(panelCamposLayout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(btnRealizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCamposLayout.setVerticalGroup(
            panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCostoDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantDesayuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCostoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(23, 23, 23)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCostoCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal))
                .addGap(62, 62, 62)
                .addComponent(checkBoxImprimirNota)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCampos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private void establecerClientes() {
        DefaultComboBoxModel modeloLista;
        Object[] arregloClientes;
        // Si hay clientes en la lista
        if (listaClientes.size() > 0) {
            // Se guardan en el arreglo  
            arregloClientes = listaClientes.toArray();
            modeloLista = new DefaultComboBoxModel(arregloClientes);
            comboClientes.setModel(modeloLista);
            comboClientes.setEnabled(true);
            checkBoxNuevoCli.setEnabled(true);
        } else {
            // Se guarda un solo valor indicando el resultado de la búsqueda
            arregloClientes = new Object[1];
            arregloClientes[0] = "-------SIN CLIENTES DISPONIBLES------";
            modeloLista = new DefaultComboBoxModel(arregloClientes);
            comboClientes.setModel(modeloLista);

            // Se desactivan todos los componentes inferiores
            desactivarCampos(panelCampos, false);
            checkBoxNuevoCli.setEnabled(false);
            checkBoxNuevoCli.setSelected(true);
        }

    }
    private void comboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientesActionPerformed

    }//GEN-LAST:event_comboClientesActionPerformed

    private void btnRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVentaActionPerformed
        ConfirmacionVenta conf = new ConfirmacionVenta(parent, true, total);
        conf.setVisible(true);
        if (conf.aceptado) {
            Cliente cliente = null;
            int de = (Integer) txtCantDesayuno.getValue();
            int co = (Integer) txtCantComida.getValue();
            int ce = (Integer) txtCantCena.getValue();
            Venta v = new Venta(0, new Timestamp(Calendar.getInstance().getTimeInMillis()), Control.usuarioActivo);
            // Si es modificacion de un cliente
            if (!checkBoxNuevoCli.isSelected()) {
                cliente = (Cliente) comboClientes.getSelectedItem();
                cliente.setCreditoDesayuno(cliente.getCreditoDesayuno() + de);
                cliente.setCreditoComida(cliente.getCreditoComida() + co);
                cliente.setCreditoCena(cliente.getCreditoCena() + ce);
                // Si se genera correctamente la venta
                if (Control.ventas.agregar(v)) {
                    v = Control.ventas.consultarUltimaVenta();
                    // Se genera la venta de credito
                    VentaCredito vc = new VentaCredito(0, v, cliente, de, co, ce, total);
                    Control.ventasCredito.agregarVentaCredito(vc);
                    Control.clientes.actualizar(cliente);
                     JOptionPane.showMessageDialog(parent, "Venta realizada", "Exito", JOptionPane.INFORMATION_MESSAGE);
                     listaClientes = Control.clientes.consultarListaOrdenada();
                     establecerClientes();
                     reestableceCamposVenta();
                } else {
                    JOptionPane.showMessageDialog(parent, "No se pudo generar la venta", "Imposible", JOptionPane.ERROR_MESSAGE);
                }
            }// Si es cliente nuevo
            else{
                cliente= new Cliente(0,campoNombreCliente.getText(), de, co, ce);
                if (Control.ventas.agregar(v)) {
                    v = Control.ventas.consultarUltimaVenta();
                    Control.clientes.agregar(cliente);
                    cliente = Control.clientes.consultarLista().get(listaClientes.size());
                    // Se genera la venta de credito
                    VentaCredito vc = new VentaCredito(0, v, cliente, de, co, ce, total);
                    Control.ventasCredito.agregarVentaCredito(vc); 
                     JOptionPane.showMessageDialog(parent, "Venta realizada", "Exito", JOptionPane.INFORMATION_MESSAGE);
                     listaClientes = Control.clientes.consultarListaOrdenada();
                     establecerClientes();
                     reestableceCamposVenta();
                } else {
                    JOptionPane.showMessageDialog(parent, "No se pudo generar la venta", "Imposible", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_btnRealizarVentaActionPerformed

    private void checkBoxImprimirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxImprimirNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxImprimirNotaActionPerformed

    private void checkBoxNuevoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNuevoCliActionPerformed
        boolean acc = checkBoxNuevoCli.isSelected();

        if (acc) {
            comboClientes.setEnabled(false);
            txtNombreCliente.setEnabled(true);
            campoNombreCliente.setEnabled(true);
            desactivarCampos(panelCampos, false);
            reestableceCamposVenta();
        } else {
            campoNombreCliente.setText("");
            campoNombreCliente.setEnabled(false);
            txtNombreCliente.setEnabled(false);
            comboClientes.setEnabled(true);
            desactivarCampos(panelCampos, true);
            reestableceCamposVenta();
            checkBoxImprimirNota.setEnabled(false);
            btnRealizarVenta.setEnabled(false);
        }

    }//GEN-LAST:event_checkBoxNuevoCliActionPerformed

    private void campoNombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreClienteKeyReleased
        boolean hayTexto = !campoNombreCliente.getText().equals("");

        desactivarCampos(panelCampos, hayTexto);
        txtCostoDesayuno.setEnabled(false);
        txtCostoComida.setEnabled(false);
        txtCostoCena.setEnabled(false);
        verificarCampos();
    }//GEN-LAST:event_campoNombreClienteKeyReleased

    private void txtCantDesayunoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCantDesayunoStateChanged
        verificarCampos();
    }//GEN-LAST:event_txtCantDesayunoStateChanged

    private void txtCantComidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCantComidaStateChanged
        verificarCampos();
    }//GEN-LAST:event_txtCantComidaStateChanged

    private void txtCantCenaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCantCenaStateChanged
        verificarCampos();
    }//GEN-LAST:event_txtCantCenaStateChanged

    private void txtCostoDesayunoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCostoDesayunoStateChanged
        verificarCampos();
    }//GEN-LAST:event_txtCostoDesayunoStateChanged

    private void txtCostoComidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCostoComidaStateChanged
        verificarCampos();
    }//GEN-LAST:event_txtCostoComidaStateChanged

    private void txtCostoCenaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCostoCenaStateChanged
        verificarCampos();
    }//GEN-LAST:event_txtCostoCenaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JTextField campoNombreCliente;
    private javax.swing.JCheckBox checkBoxImprimirNota;
    private javax.swing.JCheckBox checkBoxNuevoCli;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JSpinner txtCantCena;
    private javax.swing.JSpinner txtCantComida;
    private javax.swing.JSpinner txtCantDesayuno;
    private javax.swing.JSpinner txtCostoCena;
    private javax.swing.JSpinner txtCostoComida;
    private javax.swing.JSpinner txtCostoDesayuno;
    private javax.swing.JLabel txtNombreCliente;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
private void verificarCampos() {
        int de = (Integer) txtCantDesayuno.getValue();
        if (de > 0) {
            txtCostoDesayuno.setEnabled(true);
        } else {
            txtCostoDesayuno.setEnabled(false);
            txtCostoDesayuno.setValue(0f);
        }
        int co = (Integer) txtCantComida.getValue();
        if (co > 0) {
            txtCostoComida.setEnabled(true);
        } else {
            txtCostoComida.setEnabled(false);
            txtCostoComida.setValue(0f);
        }
        int ce = (Integer) txtCantCena.getValue();
        if (ce > 0) {
            txtCostoCena.setEnabled(true);
        } else {
            txtCostoCena.setEnabled(false);
            txtCostoCena.setValue(0f);
        }
        float costoD = (Float) txtCostoDesayuno.getValue();
        float costoCo = (Float) txtCostoComida.getValue();
        float costoCe = (Float) txtCostoCena.getValue();
        total = costoD + costoCo + costoCe;
        txtTotal.setText(String.format("%.2f", total));
        boolean condi = de + co + ce > 0;
        checkBoxImprimirNota.setEnabled(condi);
        btnRealizarVenta.setEnabled(condi);
    }

    private void desactivarCampos(Container componente, boolean activo) {
        for (Component c : componente.getComponents()) {
            c.setEnabled(activo);
        }
    }

    private void reestableceCamposVenta() {

        txtCantDesayuno.setValue(0);
        txtCostoDesayuno.setEnabled(false);
        txtCostoDesayuno.setValue(0f);

        txtCantComida.setValue(0);
        txtCostoComida.setEnabled(false);
        txtCostoComida.setValue(0f);

        txtCantCena.setValue(0);
        txtCostoCena.setEnabled(false);
        txtCostoComida.setValue(0f);

        txtTotal.setText("0.00");
    }
}
