/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Vender;

import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import logica.Control;
import negocio.Platillo;
import negocio.PlatilloMenu;
import negocio.ReservaPlatillo;

/**
 *
 * @author ed000
 */
public class Seleccionreserva extends javax.swing.JDialog {

    /**
     * Creates new form Seleccionreserva
     */
    private ArrayList<ReservaPlatillo> listaReservasDia;
    public ReservaPlatillo reservaSeleccionada;
    public Seleccionreserva(java.awt.Frame parent, boolean modal, ArrayList<ReservaPlatillo> listaReservasDia ) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.listaReservasDia = listaReservasDia;
        /// Crea los modelos para establecer en la tabla de menu y en el combobox
        Object[] columnas = {"Cliente", "Platillo", "Cantidad"};
        Object[][] modelo = new Object[listaReservasDia.size()][3];
        int x = 0;
        for (ReservaPlatillo reserva : listaReservasDia) {
            String cliente = reserva.getCliente().getNombre();
            String platillo = reserva.getPlatillo().getNombre();
            int cantidad = reserva.getCantidad();
            modelo[x][0] = cliente;
            modelo[x][1] = platillo;
            modelo[x][2] = cantidad;
            x++;
        }
        // Se establece el modelo en la tabla con los datos
        tablaReservasDia.setDefaultEditor(Object.class, null);
        tablaReservasDia.setModel(new DefaultTableModel(modelo, columnas));
        tablaReservasDia.setCellSelectionEnabled(false);
        tablaReservasDia.setRowSelectionAllowed(true);
         // Se agrega el evento a la tabla al seleccionar una reserva
            tablaReservasDia.addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int row = tablaReservasDia.rowAtPoint(evt.getPoint());
                    int col = tablaReservasDia.columnAtPoint(evt.getPoint());
                    btnAceptar.setEnabled(row >= 0 && col >= 0);

                }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReservasDia = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione reserva");

        tablaReservasDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Platillo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaReservasDia.setColumnSelectionAllowed(true);
        tablaReservasDia.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaReservasDia);
        tablaReservasDia.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione la reserva del cliente");

        btnAceptar.setText("ACEPTAR");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(47, 47, 47)
                        .addComponent(btnAceptar)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      int index = tablaReservasDia.getSelectedRow();
      reservaSeleccionada = listaReservasDia.get(index);
      dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReservasDia;
    // End of variables declaration//GEN-END:variables
}
